/*
 * Gosocket Payment API
 * Synchronize payments API
 *
 * OpenAPI spec version: v1
 * Contact: developerteam@gosocket.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.notification.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.notification.model.GosocketPaymentDataModelsRedbancPaymentModel;

import java.io.IOException;

/**
 * GosocketPaymentDataModelsRedbancRedbancPaymentModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-13T18:41:34.367Z")
public class GosocketPaymentDataModelsRedbancRedbancPaymentModel {
  @SerializedName("orderId")
  private String orderId = null;

  @SerializedName("payment")
  private GosocketPaymentDataModelsRedbancPaymentModel payment = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  public GosocketPaymentDataModelsRedbancRedbancPaymentModel orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public GosocketPaymentDataModelsRedbancRedbancPaymentModel payment(GosocketPaymentDataModelsRedbancPaymentModel payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @ApiModelProperty(value = "")
  public GosocketPaymentDataModelsRedbancPaymentModel getPayment() {
    return payment;
  }

  public void setPayment(GosocketPaymentDataModelsRedbancPaymentModel payment) {
    this.payment = payment;
  }

  public GosocketPaymentDataModelsRedbancRedbancPaymentModel transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(value = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GosocketPaymentDataModelsRedbancRedbancPaymentModel gosocketPaymentDataModelsRedbancRedbancPaymentModel = (GosocketPaymentDataModelsRedbancRedbancPaymentModel) o;
    return Objects.equals(this.orderId, gosocketPaymentDataModelsRedbancRedbancPaymentModel.orderId) &&
        Objects.equals(this.payment, gosocketPaymentDataModelsRedbancRedbancPaymentModel.payment) &&
        Objects.equals(this.transactionId, gosocketPaymentDataModelsRedbancRedbancPaymentModel.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, payment, transactionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GosocketPaymentDataModelsRedbancRedbancPaymentModel {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

