/*
 * Gosocket Payment API
 * Synchronize payments API
 *
 * OpenAPI spec version: v1
 * Contact: developerteam@gosocket.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.notification.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GosocketPaymentDataModelsRedbancAccountPayment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-13T18:41:34.367Z")
public class GosocketPaymentDataModelsRedbancAccountPayment {
  @SerializedName("destinationDNI")
  private String destinationDNI = null;

  @SerializedName("identification")
  private String identification = null;

  @SerializedName("name")
  private String name = null;

  public GosocketPaymentDataModelsRedbancAccountPayment destinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
    return this;
  }

   /**
   * Get destinationDNI
   * @return destinationDNI
  **/
  @ApiModelProperty(value = "")
  public String getDestinationDNI() {
    return destinationDNI;
  }

  public void setDestinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
  }

  public GosocketPaymentDataModelsRedbancAccountPayment identification(String identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public String getIdentification() {
    return identification;
  }

  public void setIdentification(String identification) {
    this.identification = identification;
  }

  public GosocketPaymentDataModelsRedbancAccountPayment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GosocketPaymentDataModelsRedbancAccountPayment gosocketPaymentDataModelsRedbancAccountPayment = (GosocketPaymentDataModelsRedbancAccountPayment) o;
    return Objects.equals(this.destinationDNI, gosocketPaymentDataModelsRedbancAccountPayment.destinationDNI) &&
        Objects.equals(this.identification, gosocketPaymentDataModelsRedbancAccountPayment.identification) &&
        Objects.equals(this.name, gosocketPaymentDataModelsRedbancAccountPayment.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationDNI, identification, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GosocketPaymentDataModelsRedbancAccountPayment {\n");
    
    sb.append("    destinationDNI: ").append(toIndentedString(destinationDNI)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

