/*
 * Gosocket Payment API
 * Synchronize payments API
 *
 * OpenAPI spec version: v1
 * Contact: developerteam@gosocket.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.notification.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.notification.model.GosocketPaymentDataModelsMobileMobilePaymentItem;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GosocketPaymentDataModelsMobileMobilePaymentModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-13T18:41:34.367Z")
public class GosocketPaymentDataModelsMobileMobilePaymentModel {
  @SerializedName("Username")
  private String username = null;

  @SerializedName("Email")
  private String email = null;

  @SerializedName("CountryId")
  private String countryId = null;

  @SerializedName("Payments")
  private List<GosocketPaymentDataModelsMobileMobilePaymentItem> payments = null;

  public GosocketPaymentDataModelsMobileMobilePaymentModel username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public GosocketPaymentDataModelsMobileMobilePaymentModel email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public GosocketPaymentDataModelsMobileMobilePaymentModel countryId(String countryId) {
    this.countryId = countryId;
    return this;
  }

   /**
   * Get countryId
   * @return countryId
  **/
  @ApiModelProperty(value = "")
  public String getCountryId() {
    return countryId;
  }

  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  public GosocketPaymentDataModelsMobileMobilePaymentModel payments(List<GosocketPaymentDataModelsMobileMobilePaymentItem> payments) {
    this.payments = payments;
    return this;
  }

  public GosocketPaymentDataModelsMobileMobilePaymentModel addPaymentsItem(GosocketPaymentDataModelsMobileMobilePaymentItem paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<GosocketPaymentDataModelsMobileMobilePaymentItem>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  @ApiModelProperty(value = "")
  public List<GosocketPaymentDataModelsMobileMobilePaymentItem> getPayments() {
    return payments;
  }

  public void setPayments(List<GosocketPaymentDataModelsMobileMobilePaymentItem> payments) {
    this.payments = payments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GosocketPaymentDataModelsMobileMobilePaymentModel gosocketPaymentDataModelsMobileMobilePaymentModel = (GosocketPaymentDataModelsMobileMobilePaymentModel) o;
    return Objects.equals(this.username, gosocketPaymentDataModelsMobileMobilePaymentModel.username) &&
        Objects.equals(this.email, gosocketPaymentDataModelsMobileMobilePaymentModel.email) &&
        Objects.equals(this.countryId, gosocketPaymentDataModelsMobileMobilePaymentModel.countryId) &&
        Objects.equals(this.payments, gosocketPaymentDataModelsMobileMobilePaymentModel.payments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, email, countryId, payments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GosocketPaymentDataModelsMobileMobilePaymentModel {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

