/*
 * Gosocket Payment API
 * Synchronize payments API
 *
 * OpenAPI spec version: v1
 * Contact: developerteam@gosocket.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.notification.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Paid Document in Gosocket
 */
@ApiModel(description = "Paid Document in Gosocket")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-13T18:41:34.367Z")
public class GosocketPaymentApiModelsPaidDocument {
  @SerializedName("TransactionId")
  private String transactionId = null;

  @SerializedName("BrokerDocumentGroupTransactionId")
  private String brokerDocumentGroupTransactionId = null;

  @SerializedName("DocumentGroupId")
  private String documentGroupId = null;

  @SerializedName("DocumentReceiverRut")
  private String documentReceiverRut = null;

  @SerializedName("DocumentReceiverName")
  private String documentReceiverName = null;

  @SerializedName("DocumentType")
  private Integer documentType = null;

  @SerializedName("DocumentNumber")
  private Long documentNumber = null;

  @SerializedName("DocumentAmount")
  private Double documentAmount = null;

  @SerializedName("PaymentDate")
  private OffsetDateTime paymentDate = null;

  @SerializedName("AccountingDate")
  private OffsetDateTime accountingDate = null;

  public GosocketPaymentApiModelsPaidDocument transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Id de la transacción, es único para cada documento pagado (Gosocket)
   * @return transactionId
  **/
  @ApiModelProperty(value = "Id de la transacción, es único para cada documento pagado (Gosocket)")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public GosocketPaymentApiModelsPaidDocument brokerDocumentGroupTransactionId(String brokerDocumentGroupTransactionId) {
    this.brokerDocumentGroupTransactionId = brokerDocumentGroupTransactionId;
    return this;
  }

   /**
   * Id de la transacción, es único para cada pago (Servipag)
   * @return brokerDocumentGroupTransactionId
  **/
  @ApiModelProperty(value = "Id de la transacción, es único para cada pago (Servipag)")
  public String getBrokerDocumentGroupTransactionId() {
    return brokerDocumentGroupTransactionId;
  }

  public void setBrokerDocumentGroupTransactionId(String brokerDocumentGroupTransactionId) {
    this.brokerDocumentGroupTransactionId = brokerDocumentGroupTransactionId;
  }

  public GosocketPaymentApiModelsPaidDocument documentGroupId(String documentGroupId) {
    this.documentGroupId = documentGroupId;
    return this;
  }

   /**
   * Id del grupo de documento pagado, si se pagan por ejemplo 3 documentos en una sola transferencia los 3 tendrán el mismo DocumentGroupId
   * @return documentGroupId
  **/
  @ApiModelProperty(value = "Id del grupo de documento pagado, si se pagan por ejemplo 3 documentos en una sola transferencia los 3 tendrán el mismo DocumentGroupId")
  public String getDocumentGroupId() {
    return documentGroupId;
  }

  public void setDocumentGroupId(String documentGroupId) {
    this.documentGroupId = documentGroupId;
  }

  public GosocketPaymentApiModelsPaidDocument documentReceiverRut(String documentReceiverRut) {
    this.documentReceiverRut = documentReceiverRut;
    return this;
  }

   /**
   * Rut del receptor del documento eléctronico
   * @return documentReceiverRut
  **/
  @ApiModelProperty(value = "Rut del receptor del documento eléctronico")
  public String getDocumentReceiverRut() {
    return documentReceiverRut;
  }

  public void setDocumentReceiverRut(String documentReceiverRut) {
    this.documentReceiverRut = documentReceiverRut;
  }

  public GosocketPaymentApiModelsPaidDocument documentReceiverName(String documentReceiverName) {
    this.documentReceiverName = documentReceiverName;
    return this;
  }

   /**
   * Nombre del receptor del documento eléctronico
   * @return documentReceiverName
  **/
  @ApiModelProperty(value = "Nombre del receptor del documento eléctronico")
  public String getDocumentReceiverName() {
    return documentReceiverName;
  }

  public void setDocumentReceiverName(String documentReceiverName) {
    this.documentReceiverName = documentReceiverName;
  }

  public GosocketPaymentApiModelsPaidDocument documentType(Integer documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Tipo del documento eléctronico
   * @return documentType
  **/
  @ApiModelProperty(value = "Tipo del documento eléctronico")
  public Integer getDocumentType() {
    return documentType;
  }

  public void setDocumentType(Integer documentType) {
    this.documentType = documentType;
  }

  public GosocketPaymentApiModelsPaidDocument documentNumber(Long documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * Folio del documento eléctronico
   * @return documentNumber
  **/
  @ApiModelProperty(value = "Folio del documento eléctronico")
  public Long getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(Long documentNumber) {
    this.documentNumber = documentNumber;
  }

  public GosocketPaymentApiModelsPaidDocument documentAmount(Double documentAmount) {
    this.documentAmount = documentAmount;
    return this;
  }

   /**
   * Monto del documento eléctronico
   * @return documentAmount
  **/
  @ApiModelProperty(value = "Monto del documento eléctronico")
  public Double getDocumentAmount() {
    return documentAmount;
  }

  public void setDocumentAmount(Double documentAmount) {
    this.documentAmount = documentAmount;
  }

  public GosocketPaymentApiModelsPaidDocument paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * Fecha de Pago en Gosocket
   * @return paymentDate
  **/
  @ApiModelProperty(value = "Fecha de Pago en Gosocket")
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }

  public GosocketPaymentApiModelsPaidDocument accountingDate(OffsetDateTime accountingDate) {
    this.accountingDate = accountingDate;
    return this;
  }

   /**
   * Fecha Contable (Servipag)
   * @return accountingDate
  **/
  @ApiModelProperty(value = "Fecha Contable (Servipag)")
  public OffsetDateTime getAccountingDate() {
    return accountingDate;
  }

  public void setAccountingDate(OffsetDateTime accountingDate) {
    this.accountingDate = accountingDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GosocketPaymentApiModelsPaidDocument gosocketPaymentApiModelsPaidDocument = (GosocketPaymentApiModelsPaidDocument) o;
    return Objects.equals(this.transactionId, gosocketPaymentApiModelsPaidDocument.transactionId) &&
        Objects.equals(this.brokerDocumentGroupTransactionId, gosocketPaymentApiModelsPaidDocument.brokerDocumentGroupTransactionId) &&
        Objects.equals(this.documentGroupId, gosocketPaymentApiModelsPaidDocument.documentGroupId) &&
        Objects.equals(this.documentReceiverRut, gosocketPaymentApiModelsPaidDocument.documentReceiverRut) &&
        Objects.equals(this.documentReceiverName, gosocketPaymentApiModelsPaidDocument.documentReceiverName) &&
        Objects.equals(this.documentType, gosocketPaymentApiModelsPaidDocument.documentType) &&
        Objects.equals(this.documentNumber, gosocketPaymentApiModelsPaidDocument.documentNumber) &&
        Objects.equals(this.documentAmount, gosocketPaymentApiModelsPaidDocument.documentAmount) &&
        Objects.equals(this.paymentDate, gosocketPaymentApiModelsPaidDocument.paymentDate) &&
        Objects.equals(this.accountingDate, gosocketPaymentApiModelsPaidDocument.accountingDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, brokerDocumentGroupTransactionId, documentGroupId, documentReceiverRut, documentReceiverName, documentType, documentNumber, documentAmount, paymentDate, accountingDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GosocketPaymentApiModelsPaidDocument {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    brokerDocumentGroupTransactionId: ").append(toIndentedString(brokerDocumentGroupTransactionId)).append("\n");
    sb.append("    documentGroupId: ").append(toIndentedString(documentGroupId)).append("\n");
    sb.append("    documentReceiverRut: ").append(toIndentedString(documentReceiverRut)).append("\n");
    sb.append("    documentReceiverName: ").append(toIndentedString(documentReceiverName)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    documentAmount: ").append(toIndentedString(documentAmount)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    accountingDate: ").append(toIndentedString(accountingDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

