/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreditorAccountDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-05T15:32:10.832Z")
public class CreditorAccountDTO {
  @SerializedName("destinationDNI")
  private String destinationDNI = null;

  @SerializedName("identification")
  private String identification = null;
  
  @SerializedName("secondaryIdentification")
  private String secondaryIdentification = null;

  @SerializedName("name")
  private String name = null;

  public CreditorAccountDTO destinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
    return this;
  }

   /**
   * Get destinationDNI
   * @return destinationDNI
  **/
  @ApiModelProperty(value = "")
  public String getDestinationDNI() {
    return destinationDNI;
  }

  public void setDestinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
  }

  public CreditorAccountDTO identification(String identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public String getIdentification() {
    return identification;
  }

  public void setIdentification(String identification) {
    this.identification = identification;
  }
  
  @ApiModelProperty(value = "")
  public String getSecondaryIdentification() {
		return secondaryIdentification;
	}

	public void setSecondaryIdentification(String secundaryIdentification) {
		this.secondaryIdentification = secundaryIdentification;
	}
	
	public CreditorAccountDTO secundaryIdentification(String secondaryIdentification) {
		this.secondaryIdentification = secondaryIdentification;
		    return this;
		  }

  public CreditorAccountDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditorAccountDTO creditorAccountDTO = (CreditorAccountDTO) o;
    return Objects.equals(this.destinationDNI, creditorAccountDTO.destinationDNI) &&
        Objects.equals(this.identification, creditorAccountDTO.identification) &&
        Objects.equals(this.secondaryIdentification, creditorAccountDTO.secondaryIdentification) &&
        Objects.equals(this.name, creditorAccountDTO.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationDNI, identification, name, secondaryIdentification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditorAccountDTO {\n");
    
    sb.append("    destinationDNI: ").append(toIndentedString(destinationDNI)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    secondaryIdentification: ").append(toIndentedString(secondaryIdentification)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

